services:
  postgres_db:
    image: postgres:16-alpine
    container_name: replanted_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./apps/Server
      dockerfile: Dockerfile
    container_name: replanted_app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres_db:
        condition: service_healthy

  app_Client:
    build:
      context: ./apps/ClientServer
      dockerfile: Dockerfile
    container_name: replanted_app_client
    ports:
      - "${APP_CLIENT_PORT}:8082"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres_db:
        condition: service_healthy

  client:
    build:
      context: ./apps/Client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: replanted-client
    depends_on:
      - app
    ports:
      - "${CLIENT_PORT}:80"
    restart: unless-stopped

  sensor-mock:
    build:
      context: ./apps/ArtificialEsp
      dockerfile: dockerfile
    container_name: replanted-sensor-mock
    ports:
      - "${SENSOR_MOCK_PORT}:8085"
    restart: unless-stopped
    networks:
      - replanted-network

networks:
  replanted-network:
    driver: bridge

volumes:
  postgres_data: