// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RePlanted.Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801115949_AddActuatorDevicesManyToManyGoMapped")]
    partial class AddActuatorDevicesManyToManyGoMapped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantActuatorDevice", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("ActuatorDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("PlantId", "ActuatorDeviceId");

                    b.HasIndex("ActuatorDeviceId");

                    b.ToTable("PlantActuatorDevices", (string)null);
                });

            modelBuilder.Entity("RePlanted.Server.Models.ActuatorDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EffectStrength")
                        .HasColumnType("double precision");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoCommandPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoStateField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetParameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActuatorDevices");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LightHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("WateringIntervalDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParametersId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParametersId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantActuatorDevice", b =>
                {
                    b.HasOne("RePlanted.Server.Models.ActuatorDevice", null)
                        .WithMany()
                        .HasForeignKey("ActuatorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RePlanted.Server.Models.ActuatorDevice", b =>
                {
                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.OwnsOne("RePlanted.Server.Models.Range", "Humidity", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.OwnsOne("RePlanted.Server.Models.Range", "Temperature", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.Navigation("Humidity")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });

            modelBuilder.Entity("RePlanted.Server.Models.Plant", b =>
                {
                    b.HasOne("RePlanted.Server.Models.Parameters", "Parameters")
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId");

                    b.Navigation("Parameters");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
