// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RePlanted.Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904105708_AddAlerts")]
    partial class AddAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantActuatorDevice", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("ActuatorDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("PlantId", "ActuatorDeviceId");

                    b.HasIndex("ActuatorDeviceId");

                    b.ToTable("PlantActuatorDevices", (string)null);
                });

            modelBuilder.Entity("RePlanted.Server.Models.ActuatorDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EffectStrength")
                        .HasColumnType("double precision");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalDeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("SensorFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TargetParameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActuatorDevices");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "SourceKey", "AcknowledgedAtUtc");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("RePlanted.Server.Models.AutomationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActuatorDeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastTriggeredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("ScheduleEndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ScheduleStartTime")
                        .HasColumnType("interval");

                    b.Property<int>("SensorDeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("SensorField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActuatorDeviceId");

                    b.HasIndex("PlantId");

                    b.HasIndex("SensorDeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LightHoursPerDay")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("LightScheduleEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("LightScheduleStart")
                        .HasColumnType("interval");

                    b.Property<int>("WateringIntervalDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParametersId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParametersId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("RePlanted.Server.Models.TelemetryBucket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("HumidityMax")
                        .HasColumnType("integer");

                    b.Property<int>("HumidityMin")
                        .HasColumnType("integer");

                    b.Property<double>("HumiditySum")
                        .HasColumnType("double precision");

                    b.Property<bool>("LastLampState")
                        .HasColumnType("boolean");

                    b.Property<bool>("LastPumpState")
                        .HasColumnType("boolean");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("SoilMoistureMax")
                        .HasColumnType("integer");

                    b.Property<int>("SoilMoistureMin")
                        .HasColumnType("integer");

                    b.Property<double>("SoilMoistureSum")
                        .HasColumnType("double precision");

                    b.Property<int>("TemperatureMax")
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureMin")
                        .HasColumnType("integer");

                    b.Property<double>("TemperatureSum")
                        .HasColumnType("double precision");

                    b.Property<int>("WaterLevelMax")
                        .HasColumnType("integer");

                    b.Property<int>("WaterLevelMin")
                        .HasColumnType("integer");

                    b.Property<double>("WaterLevelSum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BucketStartUtc");

                    b.HasIndex("DeviceId", "BucketStartUtc")
                        .IsUnique();

                    b.ToTable("TelemetryBuckets");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantActuatorDevice", b =>
                {
                    b.HasOne("RePlanted.Server.Models.ActuatorDevice", null)
                        .WithMany()
                        .HasForeignKey("ActuatorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RePlanted.Server.Models.ActuatorDevice", b =>
                {
                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Alert", b =>
                {
                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.AutomationRule", b =>
                {
                    b.HasOne("RePlanted.Server.Models.ActuatorDevice", "ActuatorDevice")
                        .WithMany()
                        .HasForeignKey("ActuatorDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.ActuatorDevice", "SensorDevice")
                        .WithMany()
                        .HasForeignKey("SensorDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActuatorDevice");

                    b.Navigation("Plant");

                    b.Navigation("SensorDevice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.OwnsOne("RePlanted.Server.Models.Range", "Humidity", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.OwnsOne("RePlanted.Server.Models.Range", "Temperature", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.Navigation("Humidity")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });

            modelBuilder.Entity("RePlanted.Server.Models.Plant", b =>
                {
                    b.HasOne("RePlanted.Server.Models.Parameters", "Parameters")
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId");

                    b.Navigation("Parameters");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
