using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Server.Migrations
{
    /// <inheritdoc />
    public partial class AddActuatorDevicesManyToManyTargetParameterOnly : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ActuatorDevices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "TargetParameter" text NOT NULL,
                    "EffectType" text NOT NULL,
                    "EffectStrength" double precision NOT NULL,
                    "IsEnabled" boolean NOT NULL,
                    CONSTRAINT "PK_ActuatorDevices" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_ActuatorDevices_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "ActuatorDevices"
                DROP COLUMN IF EXISTS "GoCommand",
                DROP COLUMN IF EXISTS "GoCommandPath",
                DROP COLUMN IF EXISTS "GoStateField";
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "PlantActuatorDevices" (
                    "PlantId" integer NOT NULL,
                    "ActuatorDeviceId" integer NOT NULL,
                    CONSTRAINT "PK_PlantActuatorDevices" PRIMARY KEY ("PlantId", "ActuatorDeviceId"),
                    CONSTRAINT "FK_PlantActuatorDevices_ActuatorDevices_ActuatorDeviceId" FOREIGN KEY ("ActuatorDeviceId") REFERENCES "ActuatorDevices" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PlantActuatorDevices_Plants_PlantId" FOREIGN KEY ("PlantId") REFERENCES "Plants" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_ActuatorDevices_UserId"
                ON "ActuatorDevices" ("UserId");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_PlantActuatorDevices_ActuatorDeviceId"
                ON "PlantActuatorDevices" ("ActuatorDeviceId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"PlantActuatorDevices\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"ActuatorDevices\";");
        }
    }
}
