// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using RePlanted.Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122093319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LightHoursPerDay")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("WateringIntervalDays")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RePlanted.Server.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ParametersId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParametersId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("RePlanted.Server.Models.Parameters", b =>
                {
                    b.OwnsOne("RePlanted.Server.Models.Range", "Humidity", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<int>("Max")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<int>("Min")
                                .HasColumnType("NUMBER(10)");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.OwnsOne("RePlanted.Server.Models.Range", "Temperature", b1 =>
                        {
                            b1.Property<int>("ParametersId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<int>("Max")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<int>("Min")
                                .HasColumnType("NUMBER(10)");

                            b1.HasKey("ParametersId");

                            b1.ToTable("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ParametersId");
                        });

                    b.Navigation("Humidity")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });

            modelBuilder.Entity("RePlanted.Server.Plant", b =>
                {
                    b.HasOne("RePlanted.Server.Models.Parameters", "Parameters")
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RePlanted.Server.Models.User", null)
                        .WithMany("Plants")
                        .HasForeignKey("UserId");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("RePlanted.Server.Models.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
